# 此文件由模板生成。请根据你的键盘实际情况进行修改。
# 访问 https://zmk.dev/docs/development/hardware-integration/new-shield 获取更多说明。

# 当用户添加此键盘时，该文件将被复制到用户的配置（config）目录中。
# 你可以在这里定义用户可能经常需要设置的各种 Kconfig 选项，
# 但请先将它们保持在注释状态（即前面带有 #），例如：

# 取消注释以启用编码器（通常指旋钮）
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 取消注释以启用显示屏（OLED 等）
# CONFIG_ZMK_DISPLAY=y

# 开启深度睡眠模式 (默认通常是关闭的)
CONFIG_ZMK_SLEEP=y

# 键盘进入空闲状态的延迟时间 (单位：毫秒)。默认 30000 毫秒 (30秒)
# 在这个时间后，RGB 灯光和屏幕会关闭。
CONFIG_ZMK_IDLE_TIMEOUT=30000

# 键盘进入深度睡眠的延迟时间 (单位：毫秒)。默认 900000 毫秒 (15分钟)
# 在这个时间后，蓝牙会断开以节省最大电量。这里设置为 15 分钟。
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 让主机 (Central) 定期去获取外设 (Peripheral) 的电量
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# 让主机把获取到的双边电量数据代理上报给连接的设备 (电脑/手机)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y